---
title: "EDA"
author: "Yuqian Chen"
date: "2022-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

````{r}
library(VGAM)
library(cdabookdb)
library(cdabookfunc)
library(tidyr)
#library(openxlsx)
library(stringr)
library(splitTools)
library(car)

data = read.csv("final_data1000.csv")
data = subset.data.frame(data, data$Total_hour!=0)
```
```{r}
cor.matrix=cor(data[,c(2,3,6:19,20)])
library(car)
corrplot::corrplot(cor.matrix,method = "number",type = "lower",tl.cex = 0.5, tl.col = "red", cl.cex = 0.8,number.cex = 0.5)
```

```{r}
Y = data["comment_star"]
factorY = factor(c(t(Y)))
data$OrderStar = ordered(factorY,labels=c("1","2","3","4","5"))
col_list = c(colnames(data))
data[,c(1:3,6:16,18,19,20)] <- lapply(data[,c(1:3,6:16,18,19,20)], factor)
```

```{r 80%}
train.rows <- sample(rownames(data), dim(data)[1]*0.8)
train <- data[train.rows,]

test.rows <- sample(rownames(data), dim(data)[1]*0.2)
test <- data[test.rows,]
```
```{r 90%}
train90.rows <- sample(rownames(data), dim(data)[1]*0.9)
train90 <- data[train90.rows,]

test90.rows <- sample(rownames(data), dim(data)[1]*0.1)
test90 <- data[test90.rows,]

ggplot(data) + 
  geom_histogram(aes(comment_star), stat="count")
```


```{r multicol and m1}
init1 = lm(comment_star ~ businessparking + RestaurantsReservations + HasTV
           + Alcohol 
          + RestaurantsGoodForGroups + WiFi + garage + street + lot + valet + dinner + Total_hour + acceptable_noise + upscale_classy, data = data)
vif(init1)
init11 = lm(comment_star ~ BikeParking, data = data)
summary(init11)


m1 = vglm(OrderStar ~ BikeParking +
          RestaurantsReservations + HasTV 
          + Alcohol 
          + RestaurantsGoodForGroups + WiFi 
          + garage + street + lot + valet 
          + dinner + Total_hour + acceptable_noise + upscale_classy,family = cumulative(parallel = TRUE),data = train)
summary(m1)
anova(m1,test = "LRT")
```
```{r}
X2 <- sum(resid(m1, type = "pearson") ^ 2)
x2_pvalue <- 1- pchisq(X2, 42738)
c(X2 = X2, pvalue = x2_pvalue)
```

```{r m2}
m2 = vglm(OrderStar ~  BikeParking 
          + RestaurantsReservations 
          #+ HasTV 
          + Alcohol
          #+ RestaurantsGoodForGroups 
          + WiFi 
          + garage 
          + street
          + lot
          + valet 
          + dinner 
          + Total_hour 
          + acceptable_noise 
          + upscale_classy,family = cumulative(parallel = TRUE),data = train)
summary(m2)
#anova(m2,test = "LRT")
```

```{r m2 90}
m22 = vglm(OrderStar ~  BikeParking 
          + RestaurantsReservations 
          + HasTV 
          + Alcohol
          #+ RestaurantsGoodForGroups 
          + WiFi 
          + garage 
          + street
          + lot
          + valet 
          + dinner 
          + Total_hour 
          + acceptable_noise 
          + upscale_classy,family = cumulative(parallel = TRUE),data = train90)
summary(m22)
```
```{r}
X2 <- sum(resid(m2, type = "pearson") ^ 2)
x2_pvalue <- 1- pchisq(X2, 42740)

c(X2 = X2, pvalue = x2_pvalue)
```

```{r m1 vs m2}
anova(m1,m2,type = 'I')
```

```{r m3}
m3 = vglm(OrderStar ~  BikeParking 
          #+ RestaurantsReservations 
          #+ HasTV 
          + RestaurantsGoodForGroups 
          + WiFi 
          + garage 
          #+ street 
          + valet 
          #+ dinner 
          + Total_hour 
          + acceptable_noise 
          + upscale_classy,family = cumulative(parallel = TRUE),data = train)
summary(m3)
anova(m2,m3,type = "I")

X2 <- sum(resid(m3, type = "pearson") ^ 2)
x2_pvalue <- 1- pchisq(X2, 42796)
c(X2 = X2, pvalue = x2_pvalue)
```
```{r accuracy}
pred_prob11<- predict(m2, type = "response", newdata = test )
predict.results1 <-as.numeric( colnames(pred_prob11)[apply(pred_prob11,1,which.max)])

misClasificError <- mean(predict.results1 == test$comment_star)
print(paste('Accuracy',misClasificError))
```
```{r accuracy90}
pred_prob11<- predict(m22, type = "response", newdata = test90 )
predict.results1 <-as.numeric( colnames(pred_prob11)[apply(pred_prob11,1,which.max)])

misClasificError <- mean(predict.results1 != test$comment_star)
print(paste('Accuracy',1-misClasificError))
```



```{r}
predict_model = function(OrderStar,comment_star,BikeParking,RestaurantsGoodForGroups, WiFi,garage,street,valet,Total_hour,acceptable_noise,upscale_classy){
  columns = c('OrderStar','comment_star','BikeParking','RestaurantsGoodForGroups','WiFi','garage','street','valet','Total_hour','acceptable_noise','upscale_classy')
  test_df = data.frame(matrix(nrow = 0, ncol = length(columns)))
  colnames(test_df) = columns
  
  new_row = list('OrderStar' = OrderStar, 'comment_star' = comment_star, 'BikeParking' = BikeParking,'RestaurantsGoodForGroups' = RestaurantsGoodForGroups,'WiFi' = WiFi,
            'garage' = garage,'street' = street, 'valet' = valet,
            'Total_hour' = Total_hour,'acceptable_noise' = acceptable_noise,
            'upscale_classy' = upscale_classy)
  
  test_df = rbind(test_df,new_row)
  test_df$OrderStar = as.factor(test_df$OrderStar)
  test_df$BikeParking = as.factor(test_df$BikeParking)
  test_df$RestaurantsGoodForGroups = as.factor(test_df$RestaurantsGoodForGroups)
  test_df$WiFi = as.factor(test_df$WiFi)
  test_df$garage = as.factor(test_df$garage)
  test_df$street = as.factor(test_df$street)
  test_df$valet = as.factor(test_df$valet)
  test_df$acceptable_noise = as.factor(test_df$acceptable_noise)
  test_df$upscale_classy = as.factor(test_df$upscale_classy)
  
  pred <- predict(m2,test_df,type = "response")
  pie.prop <- as.vector(pred)
  pie.labels <- c("1 star","2 star", "3 star", "4 star","5 star")
  pie.labels <- paste(pie.labels," ",round(pie.prop,2) , sep="")
  library(RColorBrewer)
  print(paste0("The predicted probability of getting star 1 is:", round(pred[1],2)))
  print(paste0("The predicted probability of getting star 2 is:", round(pred[2],2)))
  print(paste0("The predicted probability of getting star 3 is:", round(pred[3],2)))
  print(paste0("The predicted probability of getting star 4 is:", round(pred[4],2)))
  print(paste0("The predicted probability of getting star 5 is:", round(pred[5],2)))
  return(pie(pie.prop, pie.labels, col=brewer.pal(5, "RdYlGn")))
  #return(pred)

}


pred = predict_model(4,4,1,1,1,1,0,1,55,1,1)

```










